//
//  UIConfiguration.h
//  Colombio
//
//  Created by Vlatko Šprem on 20/12/14.
//  Copyright (c) 2014 Colombio. All rights reserved.
//

#import <Foundation/Foundation.h>

//colors
static NSString *COLOR_BLACK_TRANSPARENT = @"COLOR_BLACK_TRANSPARENT";
static NSString *COLOR_WHITE_TRANSPARENT = @"COLOR_WHITE_TRANSPARENT";
static NSString *COLOR_CUSTOM_RED = @"COLOR_CUSTOM_RED";
static NSString *COLOR_TEXT_NAVIGATIONBAR_TITLE = @"COLOR_TEXT_NAVIGATIONBAR_TITLE";
static NSString *COLOR_TEXT_NAVIGATIONBAR_BUTTONLABEL = @"COLOR_TEXT_NAVIGATIONBAR_BUTTONLABEL";
static NSString *COLOR_TEXT_NAVIGATIONBAR_BUTTON = @"COLOR_TEXT_NAVIGATIONBAR_BUTTON";
static NSString *COLOR_TEXT_NAVIGATIONBAR_BUTTON_HIGHLIGHT = @"COLOR_TEXT_NAVIGATIONBAR_BUTTON_HIGHLIGHT";
static NSString *COLOR_TAGS_TEXT_NORMAL = @"COLOR_TEXT_TAGS_NORMAL";
static NSString *COLOR_TAGS_TEXT_SELECTED = @"COLOR_TEXT_TAGS_SELECTED";
static NSString *COLOR_TAGS_BACKGROUND_SELECTED = @"COLOR_TAGS_BACKGROUND_SELECTED";
static NSString *COLOR_PROGRES_BAR = @"COLOR_PROGRES_BAR";
static NSString *COLOR_WHITE_CUSTOM = @"COLOR_WHITE_CUSTOM";
static NSString *COLOR_PLACEHOLDER_NEWS_TITLE = @"COLOR_PLACEHOLDER_NEWS_TITLE";
static NSString *COLOR_TEXT_NEWS_TITLE = @"COLOR_TEXT_NEWS_TITLE";
static NSString *COLOR_TEXT_TXT_FIELD = @"COLOR_TEXT_TXT_FIELD";
static NSString *COLOR_PLACEHOLDER_TXT_FIELD = @"COLOR_PLACEHOLDER_TXT_FIELD";
static NSString *COLOR_NEWS_DEMAND_DESCRIPTION = @"COLOR_NEWS_DEMAND_DESCRIPTION";
static NSString *COLOR_NEWS_DEMAND_LIGHT_GRAY = @"COLOR_NEWS_DEMAND_LIGHT_GRAY";
static NSString *COLOR_NEXT_BUTTON = @"COLOR_NEXT_BUTTON";
static NSString *COLOR_NEXT_BUTTON_SELECTED = @"COLOR_NEXT_BUTTON_SELECTED";
static NSString *COLOR_TEXT_79_04 = @"COLOR_TEXT_79_04";

//fonts
static NSString *FONT_HELVETICA_NEUE_ULTRALIGHT = @"FONT_HELVETICA_NEUE_ULTRALIGHT";
static NSString *FONT_HELVETICA_NEUE_BOLD = @"FONT_HELVETICA_NEUE_BOLD";
static NSString *FONT_HELVETICA_NEUE_MEDIUM = @"FONT_HELVETICA_NEUE_MEDIUM";
static NSString *FONT_HELVETICA_NEUE_REGULAR_SMALL = @"FONT_HELVETICA_NEUE_REGULAR_SMALL";
static NSString *FONT_HELVETICA_NEUE_REGULAR_EXTRA_SMALL = @"FONT_HELVETICA_NEUE_REGULAR_EXTRA_SMALL";
static NSString *FONT_HELVETICA_NEUE_BOLD_SMALL = @"FONT_HELVETICA_NEUE_BOLD_SMALL";
static NSString *FONT_HELVETICA_NEUE_LIGHT_SMALL = @"FONT_HELVETICA_NEUE_LIGHT_SMALL";
static NSString *FONT_HELVETICA_NEUE_LIGHT = @"FONT_HELVETICA_NEUE_LIGHT";
static NSString *FONT_HELVETICA_NEUE_BOLD_LARGE = @"FONT_HELVETICA_NEUE_BOLD_LARGE";
static NSString *FONT_HELVETICA_NEUE_REGULAR = @"FONT_HELVETICA_NEUE_REGULAR";
static NSString *FONT_HELVETICA_NEUE_BOLD_MIDDLE = @"FONT_HELVETICA_NEUE_BOLD_MIDDLE";
static NSString *FONT_HELVETICA_NEUE_TAGS_ITALIC = @"FONT_HELVETICA_NEUE_TAGS_ITALIC";
static NSString *FONT_HELVETICA_NEUE_NEXT = @"FONT_HELVETICA_NEUE_NEXT";
static NSString *FONT_HELVETICA_NEUE_MEDIUM_15 = @"FONT_HELVETICA_NEUE_MEDIUM_15";
static NSString *FONT_HELVETICA_NEUE_BOLD_LARGE_OFFER = @"FONT_HELVETICA_NEUE_BOLD_LARGE_OFFER";
static NSString *FONT_HELVETICA_NEUE_MEDIUM_19 = @"FONT_HELVETICA_NEUE_MEDIUM_19";
static NSString *FONT_HELVETICA_NEUE_LIGHT_SMALL_15 = @"FONT_HELVETICA_NEUE_LIGHT_SMALL_15";
static NSString *FONT_HELVETICA_NEUE_REGULAR_19 = @"FONT_HELVETICA_NEUE_REGULAR_19";

//keyboard type
static NSString *KEYBOARD_DEFAULT = @"KEYBOARD_DEFAULT";
static NSString *KEYBOARD_NUMERIC = @"KEYBOARD_NUMBERIC";
static NSString *KEYBOARD_DIAL = @"KEYBOARD_DIAL";
static NSString *KEYBOARD_EMAIL = @"KEYBOARD_EMAIL";

@interface UIConfiguration : NSObject
{
    NSMutableDictionary *colorMap;
    NSMutableDictionary *fontMap;
    NSMutableDictionary *keyboardMap;
}
+ (UIConfiguration *)sharedInstance;

- (UIFont *) getFont:(NSString *) fontName;
- (UIColor *) getColor:(NSString *) colorName;
- (UIKeyboardType)getKeyboardType:(NSString*)keyboardType;
@end
